apiVersion: v1
kind: Secret
metadata:
  name: moodle-secrets
  namespace: moodle-prod
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "@@Ad1v1na#2@@"
  MARIADB_PASSWORD: "@@Ad1v1na#2@@"
  MOODLE_DB_PASS: "@@Ad1v1na#2@@"
  DB_PASS: "@@Ad1v1na#2@@"
  REDIS_PASSWORD: "@@Ad1v1na#2@@"
  MOODLE_ADMIN_PASS: "@@Ad1v1na#2@@"
---
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secrets
  namespace: moodle-prod
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "@@Ad1v1na#2@@"
  MARIADB_PASSWORD: "@@Ad1v1na#2@@"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: moodle-prod
type: Opaque
stringData:
  REDIS_PASSWORD: "@@Ad1v1na#2@@"
